name: Submit
env: 
  WOLFRAM_SYSTEM_ID: Linux-x86-64
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
on: 
  push: 
    branches:  ['release/*']
  workflow_dispatch:
jobs: 
  Submit: 
    name: Submit
    runs-on: ubuntu-latest
    container: 
      image: wolframresearch/wolframengine:latest
      options: --user root
    timeout-minutes: 30
    steps: 
    - name: Checkout
      id: checkout-code-step
      uses: actions/checkout@v3
    - name: Submit
      id: submit-paclet-step
      uses: WolframResearch/submit-paclet@v1.9.0
      with: 
        paclet_cicd_version: 0.32.0
        definition_notebook: ./ResourceDefinition.nb
        resource_system_base: ${{ secrets.RESOURCE_SYSTEM_BASE }}
    - name: UploadArtifact
      id: upload-build-artifacts-step
      uses: actions/upload-artifact@v2
      with: 
        path: ${{ env.PACLET_BUILD_DIR }}
        if-no-files-found: ignore